# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmodel.proto\x1a\x19google/protobuf/any.proto\"I\n\x0b\x42oundingBox\x12\r\n\x05x_min\x18\x01 \x01(\x05\x12\r\n\x05y_min\x18\x02 \x01(\x05\x12\r\n\x05x_max\x18\x03 \x01(\x05\x12\r\n\x05y_max\x18\x04 \x01(\x05\"\xbb\x01\n\x0cImageRequest\x12#\n\x06images\x18\x01 \x03(\x0b\x32\x13.ImageRequest.Image\x1a\x85\x01\n\x05Image\x12\x12\n\nimage_path\x18\x01 \x01(\t\x12\x1c\n\x06\x62\x62oxes\x18\x03 \x03(\x0b\x32\x0c.BoundingBox\x12$\n\x06points\x18\x04 \x01(\x0b\x32\x14.google.protobuf.Any\x12$\n\x06labels\x18\x05 \x01(\x0b\x32\x14.google.protobuf.Any\"j\n\x0f\x44ictionaryEntry\x12\x12\n\nimage_path\x18\x01 \x01(\t\x12\x11\n\tprocessed\x18\x02 \x01(\x08\x12\x17\n\x0fpng_result_path\x18\x03 \x01(\t\x12\x17\n\x0ftif_result_path\x18\x04 \x01(\t\"2\n\rImageResponse\x12!\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x10.DictionaryEntry2?\n\x0eImageProcessor\x12-\n\x0cProcessImage\x12\r.ImageRequest\x1a\x0e.ImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOUNDINGBOX']._serialized_start=42
  _globals['_BOUNDINGBOX']._serialized_end=115
  _globals['_IMAGEREQUEST']._serialized_start=118
  _globals['_IMAGEREQUEST']._serialized_end=305
  _globals['_IMAGEREQUEST_IMAGE']._serialized_start=172
  _globals['_IMAGEREQUEST_IMAGE']._serialized_end=305
  _globals['_DICTIONARYENTRY']._serialized_start=307
  _globals['_DICTIONARYENTRY']._serialized_end=413
  _globals['_IMAGERESPONSE']._serialized_start=415
  _globals['_IMAGERESPONSE']._serialized_end=465
  _globals['_IMAGEPROCESSOR']._serialized_start=467
  _globals['_IMAGEPROCESSOR']._serialized_end=530
# @@protoc_insertion_point(module_scope)
